sudo: required
os: linux
services:
  - docker
language: python
python: "3.8.3"

script:
  - docker-compose -f .travis/docker-compose.yml -p workout_generator up -d
  - docker ps -a
  - docker exec -it workout_generator bash -c "cd workout_generator && pytest -v"

deploy:
  - provider: script
    script: bash ./.travis/upload_dockerhub.sh
    on:
      all_branches: true
