version: "3.4"
services:
  app:
    container_name: workout_generator
    restart: always
    build:
      context: ..
      target: test
    ports:
      - 8000:8000
    links:
      - mongo
    tty: true
  mongo:
    container_name: mongo
    image: mongo:4.4.0
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
